
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4_ACT_N]
set_property IOSTANDARD SSTL12_DCI [get_ports {DDR4_ADR[*]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {DDR4_BA[*]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {DDR4_BG[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {DDR4_CKE[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {DDR4_ODT[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {DDR4_CS_N[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {DDR4_CK_C[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {DDR4_CK_T[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports DDR4_RST_N]
set_property IOSTANDARD POD12_DCI [get_ports {DDR4_DM[*]}]
set_property IOSTANDARD POD12_DCI [get_ports {DDR4_DQ[*]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {DDR4_DQS_C[*]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {DDR4_DQS_T[*]}]

set_property PACKAGE_PIN F23 [get_ports DDR4_ACT_N]
set_property PACKAGE_PIN H26 [get_ports {DDR4_ADR[0]}]
set_property PACKAGE_PIN B25 [get_ports {DDR4_ADR[1]}]
set_property PACKAGE_PIN J25 [get_ports {DDR4_ADR[2]}]
set_property PACKAGE_PIN C26 [get_ports {DDR4_ADR[3]}]
set_property PACKAGE_PIN G26 [get_ports {DDR4_ADR[4]}]
set_property PACKAGE_PIN F25 [get_ports {DDR4_ADR[5]}]
set_property PACKAGE_PIN K25 [get_ports {DDR4_ADR[6]}]
set_property PACKAGE_PIN E25 [get_ports {DDR4_ADR[7]}]
set_property PACKAGE_PIN M26 [get_ports {DDR4_ADR[8]}]
set_property PACKAGE_PIN B26 [get_ports {DDR4_ADR[9]}]
set_property PACKAGE_PIN G22 [get_ports {DDR4_ADR[10]}]
set_property PACKAGE_PIN M25 [get_ports {DDR4_ADR[11]}]
set_property PACKAGE_PIN C24 [get_ports {DDR4_ADR[12]}]
set_property PACKAGE_PIN E26 [get_ports {DDR4_ADR[13]}]
set_property PACKAGE_PIN L23 [get_ports {DDR4_ADR[14]}]
set_property PACKAGE_PIN H22 [get_ports {DDR4_ADR[15]}]
set_property PACKAGE_PIN H21 [get_ports {DDR4_ADR[16]}]

set_property PACKAGE_PIN K26 [get_ports {DDR4_BA[0]}]
set_property PACKAGE_PIN F24 [get_ports {DDR4_BA[1]}]
set_property PACKAGE_PIN L24 [get_ports {DDR4_BG[0]}]
set_property PACKAGE_PIN L22 [get_ports {DDR4_CKE[0]}]
set_property PACKAGE_PIN F22 [get_ports {DDR4_ODT[0]}]
set_property PACKAGE_PIN D24 [get_ports {DDR4_CS_N[0]}]
set_property PACKAGE_PIN G24 [get_ports {DDR4_CK_T[0]}]
set_property PACKAGE_PIN G25 [get_ports {DDR4_CK_C[0]}]
set_property PACKAGE_PIN L25 [get_ports DDR4_RST_N]
set_property PACKAGE_PIN A22 [get_ports {DDR4_DM[0]}]
set_property PACKAGE_PIN H18 [get_ports {DDR4_DM[1]}]
set_property PACKAGE_PIN C18 [get_ports {DDR4_DM[2]}]
set_property PACKAGE_PIN G15 [get_ports {DDR4_DM[3]}]

set_property PACKAGE_PIN C22 [get_ports {DDR4_DQ[0]}]
set_property PACKAGE_PIN B24 [get_ports {DDR4_DQ[1]}]
set_property PACKAGE_PIN C23 [get_ports {DDR4_DQ[2]}]
set_property PACKAGE_PIN A24 [get_ports {DDR4_DQ[3]}]
set_property PACKAGE_PIN D21 [get_ports {DDR4_DQ[4]}]
set_property PACKAGE_PIN B22 [get_ports {DDR4_DQ[5]}]
set_property PACKAGE_PIN E21 [get_ports {DDR4_DQ[6]}]
set_property PACKAGE_PIN A25 [get_ports {DDR4_DQ[7]}]
set_property PACKAGE_PIN F19 [get_ports {DDR4_DQ[8]}]
set_property PACKAGE_PIN D20 [get_ports {DDR4_DQ[9]}]
set_property PACKAGE_PIN G21 [get_ports {DDR4_DQ[10]}]
set_property PACKAGE_PIN E18 [get_ports {DDR4_DQ[11]}]
set_property PACKAGE_PIN G20 [get_ports {DDR4_DQ[12]}]
set_property PACKAGE_PIN D19 [get_ports {DDR4_DQ[13]}]
set_property PACKAGE_PIN F18 [get_ports {DDR4_DQ[14]}]
set_property PACKAGE_PIN D18 [get_ports {DDR4_DQ[15]}]
set_property PACKAGE_PIN A19 [get_ports {DDR4_DQ[16]}]
set_property PACKAGE_PIN B17 [get_ports {DDR4_DQ[17]}]
set_property PACKAGE_PIN B19 [get_ports {DDR4_DQ[18]}]
set_property PACKAGE_PIN A15 [get_ports {DDR4_DQ[19]}]
set_property PACKAGE_PIN B20 [get_ports {DDR4_DQ[20]}]
set_property PACKAGE_PIN B15 [get_ports {DDR4_DQ[21]}]
set_property PACKAGE_PIN A20 [get_ports {DDR4_DQ[22]}]
set_property PACKAGE_PIN C17 [get_ports {DDR4_DQ[23]}]
set_property PACKAGE_PIN H17 [get_ports {DDR4_DQ[24]}]
set_property PACKAGE_PIN D16 [get_ports {DDR4_DQ[25]}]
set_property PACKAGE_PIN G16 [get_ports {DDR4_DQ[26]}]
set_property PACKAGE_PIN D15 [get_ports {DDR4_DQ[27]}]
set_property PACKAGE_PIN E15 [get_ports {DDR4_DQ[28]}]
set_property PACKAGE_PIN C16 [get_ports {DDR4_DQ[29]}]
set_property PACKAGE_PIN H16 [get_ports {DDR4_DQ[30]}]
set_property PACKAGE_PIN G17 [get_ports {DDR4_DQ[31]}]

set_property PACKAGE_PIN C21 [get_ports {DDR4_DQS_T[0]}]
set_property PACKAGE_PIN B21 [get_ports {DDR4_DQS_C[0]}]
set_property PACKAGE_PIN F20 [get_ports {DDR4_DQS_T[1]}]
set_property PACKAGE_PIN E20 [get_ports {DDR4_DQS_C[1]}]
set_property PACKAGE_PIN A17 [get_ports {DDR4_DQS_T[2]}]
set_property PACKAGE_PIN A18 [get_ports {DDR4_DQS_C[2]}]
set_property PACKAGE_PIN E16 [get_ports {DDR4_DQS_T[3]}]
set_property PACKAGE_PIN E17 [get_ports {DDR4_DQS_C[3]}]

# GTY X0Y10
set_property PACKAGE_PIN J5 [get_ports ZSFP_TXP[0]]
set_property PACKAGE_PIN J4 [get_ports ZSFP_TXN[0]]
set_property PACKAGE_PIN H2 [get_ports ZSFP_RXP[0]]
set_property PACKAGE_PIN H1 [get_ports ZSFP_RXN[0]]

# GTY X0Y11
set_property PACKAGE_PIN G5 [get_ports ZSFP_TXP[1]]
set_property PACKAGE_PIN G4 [get_ports ZSFP_TXN[1]]
set_property PACKAGE_PIN F2 [get_ports ZSFP_RXP[1]]
set_property PACKAGE_PIN F1 [get_ports ZSFP_RXN[1]]

set_property IOSTANDARD LVCMOS33 [get_ports ZSFP_CLKSCL]
set_property PACKAGE_PIN AA15 [get_ports ZSFP_CLKSCL]
set_property IOSTANDARD LVCMOS33 [get_ports ZSFP_CLKSDA]
set_property PACKAGE_PIN Y15 [get_ports ZSFP_CLKSDA]

set_property IOSTANDARD LVCMOS33 [get_ports {ZSFP_TX_DIS[*]}]
set_property PACKAGE_PIN W13 [get_ports {ZSFP_TX_DIS[0]}]
set_property PACKAGE_PIN Y13 [get_ports {ZSFP_TX_DIS[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ZSFP_RS0[*]}]
set_property PACKAGE_PIN AA13 [get_ports {ZSFP_RS0[0]}]
set_property PACKAGE_PIN W14 [get_ports {ZSFP_RS0[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ZSFP_RS1[*]}]
set_property PACKAGE_PIN W12 [get_ports {ZSFP_RS1[0]}]
set_property PACKAGE_PIN W15 [get_ports {ZSFP_RS1[1]}]

# GTY X0Y12
#set_property PACKAGE_PIN F7 [get_ports QSFP_TXP[0]]
#set_property PACKAGE_PIN F6 [get_ports QSFP_TXN[0]]
#set_property PACKAGE_PIN D2 [get_ports QSFP_RXP[0]]
#set_property PACKAGE_PIN D1 [get_ports QSFP_RXN[0]]
#
# GTY X0Y13
#set_property PACKAGE_PIN E5 [get_ports QSFP_TXP[1]]
#set_property PACKAGE_PIN E4 [get_ports QSFP_TXN[1]]
#set_property PACKAGE_PIN C4 [get_ports QSFP_RXP[1]]
#set_property PACKAGE_PIN C3 [get_ports QSFP_RXN[1]]
#
# GTY X0Y14
#set_property PACKAGE_PIN D7 [get_ports QSFP_TXP[2]]
#set_property PACKAGE_PIN D6 [get_ports QSFP_TXN[2]]
#set_property PACKAGE_PIN B2 [get_ports QSFP_RXP[2]]
#set_property PACKAGE_PIN B1 [get_ports QSFP_RXN[2]]
#
# GTY X0Y15
#set_property PACKAGE_PIN B7 [get_ports QSFP_TXP[3]]
#set_property PACKAGE_PIN B6 [get_ports QSFP_TXN[3]]
#set_property PACKAGE_PIN A4 [get_ports QSFP_RXP[3]]
#set_property PACKAGE_PIN A3 [get_ports QSFP_RXN[3]]

set_property IOSTANDARD LVCMOS33 [get_ports QSFP_CLKSCL]
set_property PACKAGE_PIN AF14 [get_ports QSFP_CLKSCL]
set_property IOSTANDARD LVCMOS33 [get_ports QSFP_CLKSDA]
set_property PACKAGE_PIN AF15 [get_ports QSFP_CLKSDA]

set_property IOSTANDARD LVCMOS33 [get_ports QSFP_I2C_SCL]
set_property PACKAGE_PIN AE15 [get_ports QSFP_I2C_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports QSFP_I2C_SDA]
set_property PACKAGE_PIN AB16 [get_ports QSFP_I2C_SDA]

set_property IOSTANDARD LVCMOS33 [get_ports QSFP_LPMODE]
set_property PACKAGE_PIN AD13 [get_ports QSFP_LPMODE]
set_property IOSTANDARD LVCMOS33 [get_ports QSFP_MODSELL]
set_property PACKAGE_PIN AD14 [get_ports QSFP_MODSELL]
set_property IOSTANDARD LVCMOS33 [get_ports QSFP_RESETL]
set_property PACKAGE_PIN AC14 [get_ports QSFP_RESETL]

set_property IOSTANDARD LVCMOS33 [get_ports QSFP_INTL]
set_property PACKAGE_PIN AC13 [get_ports QSFP_INTL]
set_property IOSTANDARD LVCMOS33 [get_ports QSFP_MODPRSL]
set_property PACKAGE_PIN AB15 [get_ports QSFP_MODPRSL]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[*]}]
set_property PACKAGE_PIN Y16 [get_ports {LED[0]}]
set_property PACKAGE_PIN W16 [get_ports {LED[1]}]
set_property PACKAGE_PIN AB14 [get_ports {LED[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports KEY]
set_property PACKAGE_PIN AD15 [get_ports KEY]

set_property IOSTANDARD LVCMOS12 [get_ports CLK_100M]
set_property PACKAGE_PIN K22 [get_ports CLK_100M]

set_property IOSTANDARD LVDS [get_ports CLK_100M_P]
set_property IOSTANDARD LVDS [get_ports CLK_100M_N]
set_property PACKAGE_PIN J23 [get_ports CLK_100M_P]

set_property PACKAGE_PIN M7 [get_ports ZSFP_CLK_P]
set_property PACKAGE_PIN M6 [get_ports ZSFP_CLK_N]

set_property PACKAGE_PIN H7 [get_ports QSFP_CLK_P]
set_property PACKAGE_PIN H6 [get_ports QSFP_CLK_N]

create_clock -period 10.000 -name CLK_100M -waveform {0.000 5.000} [get_ports CLK_100M]
create_clock -period 6.400 -name ZSFP_CLK_P -waveform {0.000 3.200} [get_ports ZSFP_CLK_P]

# 125M <-> 100M
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins mmcm2_base_0/CLKOUT1]] -group [get_clocks CLK_100M]
# 125M <-> 200M (GTX)
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins mmcm2_base_0/CLKOUT1]] -group [get_clocks -of_objects [get_pins mmcm2_base_0/CLKOUT3]]
# 200M <-> GTX RX
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins mmcm2_base_0/CLKOUT3]] -group [get_clocks -of_objects [get_pins eth_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_rx_user_clocking_internal.gen_single_instance.gtwiz_userclk_rx_inst/gen_gtwiz_userclk_rx_main.bufg_gt_usrclk2_inst/O]]
# 200M <-> GTX TX
set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins mmcm2_base_0/CLKOUT3]] -group [get_clocks -of_objects [get_pins eth_wrapper_inst/gtwizard_ultrascale_0_inst/inst/gen_gtwizard_gtye4_top.gtwizard_ultrascale_0_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_tx_user_clocking_internal.gen_single_instance.gtwiz_userclk_tx_inst/gen_gtwiz_userclk_tx_main.bufg_gt_usrclk2_inst/O]]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
